#include "colors.inc"    // The include files contain
//#include "stones.inc"    // pre-defined scene elements
#include "woods.inc"
//#include "glass.inc"
// #include "textures.inc"

//etageres
box {
  <0, 203, 0>
  <325 - 118 , 204, 40>
  texture {
    T_Wood1
  }
}
box {
  <0, 74, 0>
  <325 - 118 , 75, 20>
  texture {
    T_Wood1
  }
}
box {
  <0, 104, 0>
  <325 - 118 , 105, 20>
  texture {
    T_Wood1
  }
}
box {
  <0, 134, 0>
  <325 - 118 , 135, 20>
  texture {
    T_Wood1
  }
}
box {
  <0, 164, 0>
  <325 - 118 , 165, 20>
  texture {
    T_Wood1
  }
}
box {
  <0, 44, 0>
  <325 - 118 , 45, 20>
  texture {
    T_Wood1
  }
}
box {
  <0, 14, 0>
  <325 - 118 , 15, 20>
  texture {
    T_Wood1
    scale 100
  }
}
